#!/bin/bash

css=$(uglifycss src/style.css)
js=$(terser --compress --mangle -- src/icons.js src/filesaver.js src/har.js src/entry.js src/main.js)
escaped_js=$(echo $js | sed -e 's/\\/\\\\/g; s/\//\\\//g; s/&/\\\&/g') # https://stackoverflow.com/a/407649/390522

sed \
    -e '/-- DEVELOP --/d' \
    -e 's/<!--PROD //' \
    -e 's/ PROD-->//' \
    -e "s/.*INCLUDE_CSS.*/$css/" \
    -e "s/.*INCLUDE_JS.*/$escaped_js/" \
    index.html > dist/index.html \
    && echo "Output created at $(pwd)/dist/index.html"
